// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqhisyncoatmbmwjjdxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxaGlzeW5jb2F0bWJtd2pqZHhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgyMjY5NzYsImV4cCI6MjA1MzgwMjk3Nn0.wDqpT3ESeGuw_0BMZk8wwqzYoym2kjHVFeT8HpQRhU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);